import { useEffect, useMemo, useState } from "react";
import { api } from "../../scripts/api.js";

const emptyInvite = { email: "", message: "" };

export default function TeamPage() {
  const [organization, setOrganization] = useState(null);
  const [members, setMembers] = useState([]);
  const [invitations, setInvitations] = useState([]);
  const [invite, setInvite] = useState(emptyInvite);
  const [removing, setRemoving] = useState(null);
  const [disposition, setDisposition] = useState("retain");
  const [transferToUserId, setTransferToUserId] = useState("");
  const [status, setStatus] = useState("");
  const [error, setError] = useState(false);
  const [busy, setBusy] = useState(false);
  const [deleteDialog, setDeleteDialog] = useState(null);

  const load = async () => {
    const [orgResult, inviteResult] = await Promise.all([
      api.admin.getOrganization(), api.admin.listOrganizationInvitations(),
    ]);
    setOrganization(orgResult.organization); setMembers(orgResult.members || []); setInvitations(inviteResult.invitations || []);
  };
  useEffect(() => { api.auth.me().then(({ user }) => { if (user?.role !== "org_admin") throw new Error("Organization administrator access is required."); return load(); }).catch((err) => { setError(true); setStatus(err?.message || "Unable to load organization."); }); }, []);
  const transferableMembers = useMemo(() => members.filter((member) => member.id !== removing?.id), [members, removing]);
  const showStatus = (text, isError = false) => { setStatus(text); setError(isError); };
  const sendInvite = async (event) => { event.preventDefault(); setBusy(true); showStatus("Sending invitation..."); try { await api.admin.inviteOrganizationMember(invite.email, invite.message); setInvite(emptyInvite); await load(); showStatus("Invitation sent."); } catch (err) { showStatus(err?.message || "Invitation failed.", true); } finally { setBusy(false); } };
  const saveOrganization = async (event) => { event.preventDefault(); setBusy(true); showStatus("Saving organization settings..."); try { const payload = { name: organization.name, businessType: organization.business_type, industry: organization.industry, email: organization.email, phoneNumber: organization.phone_number, website: organization.website, logoUrl: organization.logo_url, address: organization.address, city: organization.city, region: organization.region, postalCode: organization.postal_code, country: organization.country, defaultCurrency: organization.default_currency, timezone: organization.timezone, fiscalYearStartMonth: organization.fiscal_year_start_month }; const { organization: updated } = await api.admin.updateOrganization(payload); setOrganization(updated); showStatus("Organization settings saved."); } catch (err) { showStatus(err?.message || "Unable to save organization settings.", true); } finally { setBusy(false); } };
  const updateOrg = (key, value) => setOrganization((current) => ({ ...current, [key]: value }));
  const removeMember = async (event) => { event.preventDefault(); setBusy(true); showStatus("Removing organization member..."); try { await api.admin.removeOrganizationMember(removing.id, { disposition, transferToUserId }); setRemoving(null); setDisposition("retain"); setTransferToUserId(""); await load(); showStatus("Member removed."); } catch (err) { showStatus(err?.message || "Unable to remove member.", true); } finally { setBusy(false); } };
  const transferAdministrator = async (member) => { if (!confirm(`Make ${member.full_name || member.email} the administrator? You will remain an organization member.`)) return; setBusy(true); try { const verification = await api.admin.requestOrganizationAdminTransferVerification(); const label = verification.method === "two_factor" ? "Enter the verification code sent to your email:" : "Enter your current password:"; const credential = prompt(label); if (!credential) return; await api.admin.transferOrganizationAdmin(member.id, credential); sessionStorage.removeItem("cachedUser"); location.assign('/home'); } catch (err) { showStatus(err?.message || "Unable to reassign the administrator.", true); } finally { setBusy(false); } };
  const beginOrganizationDeletion = async () => { setBusy(true); showStatus("Preparing secure organization deletion..."); try { const verification = await api.admin.requestOrganizationDeletionVerification(); setDeleteDialog({ method: verification.method, confirmationName: "", credential: "" }); showStatus(verification.message || "Confirm organization deletion."); } catch (err) { showStatus(err?.message || "Unable to verify organization deletion.", true); } finally { setBusy(false); } };
  const deleteOrganization = async (event) => { event.preventDefault(); if (deleteDialog.confirmationName !== organization.name) { showStatus("Enter the organization name exactly as shown.", true); return; } setBusy(true); showStatus("Permanently deleting the organization..."); try { await api.admin.deleteOrganization({ confirmationName: deleteDialog.confirmationName, credential: deleteDialog.credential }); sessionStorage.removeItem("cachedUser"); sessionStorage.removeItem("cachedHeaderHtml"); location.assign('/home'); } catch (err) { showStatus(err?.message || "Unable to delete the organization.", true); setBusy(false); } };
  const invitationStatus = (item) => item.accepted_at ? "Accepted" : item.revoked_at ? "Revoked" : new Date(item.expires_at) <= new Date() ? "Expired" : item.delivery_status === "failed" ? "Delivery failed" : "Pending";

  return <>
    <div id="header"></div>
    <main className="main team-main">
      <section className="team-hero"><div><p className="team-kicker">Business workspace</p><h1>Team &amp; Organization</h1><p className="subtle">Manage members, invitations, and business defaults.</p></div><div className="team-plan"><span>{organization?.subscription_status || "—"}</span><strong>{organization?.name || "Organization"}</strong></div></section>
      {status ? <p className={`status-banner ${error ? "status-error" : "status-ok"}`}>{status}</p> : null}
      <div className="team-layout">
        <section className="card team-panel"><div className="team-heading"><div><h2>Members</h2><p className="subtle">People with access to this organization.</p></div><span className="team-count">{members.length}</span></div><div className="team-member-list">{members.map((member) => <article className="team-member" key={member.id}><div className="team-avatar">{String(member.full_name || member.email).slice(0,1).toUpperCase()}</div><div><strong>{member.full_name || member.username}</strong><span>{member.email}</span><small>{member.role === "org_admin" ? "Organization administrator" : "Member"}</small></div>{member.role === "org_user" ? <div className="team-row-actions"><button className="btn btn--link" disabled={busy} onClick={() => transferAdministrator(member)}>Make Admin</button><button className="btn btn--link team-danger" onClick={() => setRemoving(member)}>Remove</button></div> : null}</article>)}</div></section>
        <section className="card team-panel"><div className="team-heading"><div><h2>Invite a member</h2><p className="subtle">Invitations remain valid for seven days.</p></div></div><form className="team-form" onSubmit={sendInvite}><label>Email address<input type="email" value={invite.email} onChange={(e) => setInvite({...invite,email:e.target.value})} required /></label><label>Personal message <span className="subtle">(optional)</span><textarea rows="3" maxLength="1000" value={invite.message} onChange={(e) => setInvite({...invite,message:e.target.value})} /></label><button className="btn btn--primary" disabled={busy}>Send Invitation</button></form></section>
        <section className="card team-panel team-panel-wide"><div className="team-heading"><div><h2>Invitations</h2><p className="subtle">Track delivery and invitation status.</p></div></div><div className="table-wrap"><table className="admin-table"><thead><tr><th>Email</th><th>Status</th><th>Sent</th><th>Expires</th><th>Actions</th></tr></thead><tbody>{invitations.length ? invitations.map((item) => { const state = invitationStatus(item); return <tr key={item.id}><td>{item.email}</td><td>{state}</td><td>{item.sent_at ? new Date(item.sent_at).toLocaleString() : "—"}</td><td>{new Date(item.expires_at).toLocaleDateString()}</td><td>{!item.accepted_at ? <><button className="btn btn--link" onClick={() => api.admin.resendOrganizationInvitation(item.id).then(load).then(() => showStatus("Invitation resent.")).catch((err) => showStatus(err.message,true))}>Resend</button>{!item.revoked_at ? <button className="btn btn--link team-danger" onClick={() => api.admin.revokeOrganizationInvitation(item.id).then(load)}>Revoke</button> : null}</> : "—"}</td></tr>; }) : <tr><td colSpan="5" className="subtle">No invitations yet.</td></tr>}</tbody></table></div></section>
        {organization ? <section className="card team-panel team-panel-wide"><div className="team-heading"><div><h2>Organization settings</h2><p className="subtle">Defaults apply across the business workspace.</p></div><div className="team-access-summary"><span>Plan: {organization.subscription_status}</span><span>Access ends: {organization.access_expires_at ? new Date(organization.access_expires_at).toLocaleDateString() : "No expiration"}</span></div></div><form className="team-form team-settings-grid" onSubmit={saveOrganization}>
          {[['name','Business name'],['business_type','Business type'],['industry','Industry'],['email','Business email'],['phone_number','Phone'],['website','Website'],['logo_url','Logo URL'],['address','Street address'],['city','City'],['region','State / province'],['postal_code','Postal code'],['country','Country'],['default_currency','Default currency'],['timezone','Timezone']].map(([key,label]) => <label key={key}>{label}<input type={key==='email'?'email':key.includes('url')||key==='website'?'url':'text'} value={organization[key] || ''} onChange={(e)=>updateOrg(key,e.target.value)} required={key==='name'||key==='email'} /></label>)}
          <label>Fiscal year starts<select value={organization.fiscal_year_start_month || 1} onChange={(e)=>updateOrg('fiscal_year_start_month',Number(e.target.value))}>{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>{new Date(2020,i,1).toLocaleString(undefined,{month:'long'})}</option>)}</select></label><div className="team-settings-submit"><button className="btn btn--primary" disabled={busy}>Save Settings</button></div></form></section> : null}
        {organization ? <section className="card team-panel team-panel-wide team-danger-zone"><div><h2>Delete organization</h2><p className="subtle">Permanently deletes this business workspace, its financial data, invitations, and memberships. User login accounts are preserved.</p></div><button className="btn team-danger-button" type="button" disabled={busy} onClick={beginOrganizationDeletion}>Delete Organization</button></section> : null}
      </div>
    </main>
    {removing ? <div className="modal" role="dialog" aria-modal="true" onMouseDown={(event) => event.target === event.currentTarget && setRemoving(null)}><div className="modal-content team-remove-modal"><h2>Remove {removing.full_name || removing.email}</h2><p>Choose how their organization data should be handled.</p><form className="team-form" onSubmit={removeMember}><label>Data handling<select value={disposition} onChange={(e)=>setDisposition(e.target.value)}><option value="retain">Retain under the organization</option><option value="transfer">Transfer ownership to another member</option><option value="archive">Archive the member’s ownership</option></select></label>{disposition==='transfer'?<label>Transfer to<select value={transferToUserId} onChange={(e)=>setTransferToUserId(e.target.value)} required><option value="">Select a member</option>{transferableMembers.map((member)=><option key={member.id} value={member.id}>{member.full_name || member.email}</option>)}</select></label>:null}<div className="team-modal-actions"><button className="btn team-danger-button" disabled={busy}>Remove Member</button><button className="btn" type="button" onClick={()=>setRemoving(null)}>Cancel</button></div></form></div></div>:null}
    {deleteDialog ? <div className="modal" role="dialog" aria-modal="true" onMouseDown={(event) => event.target === event.currentTarget && !busy && setDeleteDialog(null)}><div className="modal-content team-remove-modal"><h2>Delete {organization.name}?</h2><p>This permanently deletes the organization and all business data. User accounts will remain available.</p><form className="team-form" onSubmit={deleteOrganization}><label>Type <strong>{organization.name}</strong> to confirm<input value={deleteDialog.confirmationName} onChange={(e)=>setDeleteDialog({...deleteDialog,confirmationName:e.target.value})} autoComplete="off" required /></label><label>{deleteDialog.method === 'two_factor' ? 'Email verification code' : 'Current password'}<input type={deleteDialog.method === 'two_factor' ? 'text' : 'password'} value={deleteDialog.credential} onChange={(e)=>setDeleteDialog({...deleteDialog,credential:e.target.value})} autoComplete="off" required /></label><div className="team-modal-actions"><button className="btn team-danger-button" disabled={busy || deleteDialog.confirmationName !== organization.name}>Permanently Delete Organization</button><button className="btn" type="button" disabled={busy} onClick={()=>setDeleteDialog(null)}>Cancel</button></div></form></div></div> : null}
    <div id="footer"></div>
  </>;
}
